name: Build/Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: linz/action-typescript@v18
      
      - name: Create github release
        if: startsWith(github.ref, 'refs/tags/v')
        run: npx conventional-github-releaser -p angular
        env:
          CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Publish to NPM
        if: startsWith(github.ref, 'refs/tags/v')
        run: npx lerna publish from-git --yes
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN_LINZJS}}
